### ISSUE TITLE
Set up and decide upon how to save credentials

### ISSUE THREAD

**Issue by yannikbuhl** [CorrelAid/restatis#1]

**Comment by yannikbuhl** [comment]
Possibilities: use {keyring} or use .Renviron (plain text)

**Comment by long39ng** [comment]
Another possibility: {httr2} has functions to [scramble secrets](https://httr2.r-lib.org/articles/wrapping-apis.html#secret-management) so that they are not visible as plain text. We are going to use {httr2} anyway and can therefore avoid dependency on {keyring}.
