### ISSUE TITLE
gen_catalogue(): Error with the query "51*" (foreign trade)

### ISSUE THREAD

**Issue by dakilian** [CorrelAid/restatis#21]
The example in the description works (`object <- gen_catalogue(code = "12*", detailed = T)`) but the query `object <- gen_catalogue(code = "51*", detailed = T)` produces an error.  
The rlang error message: 
```
Error in `$<-`:
! Assigned data `apply(...)` must be compatible with existing data.
✖ Existing data has 79 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 0 to size 79.
```
"51*" is listed as "Außenhandel" in the evas_list.  I am not able to solve the problem. Can anyone reproduce the error and help? Thanks.

**Comment by KovaZo** [comment]
Hi @dakilian,

Thank you for using the function and your helpful input regarding this issue. We are working on a new release of the package to fix this male behavior. The error is reproducible, and we found a way to fix it. 
Let me know if you need a version that works without the error (and you don`t want to wait for the new release). 
I am happy to help. 

Best,
Zoran
