### ISSUE TITLE
Add 'logincheck' to the adding of credentials

### ISSUE THREAD

**Issue by yannikbuhl** [CorrelAid/restatis#28]
Once the user adds his credentials, as of now there is no check whether it worked. The API provides the 'logincheck' endpoint where one could check the login worked. We should implement this in the respective function and give an error if the login does not work.

This will be coming in the next update.

**Comment by bergnerjonas** [comment]
@yannikbuhl 
Hi do you actively work on this issue - otherwise I could help out :)
