### ISSUE TITLE
100 lines output limit in  gen_val2var() ?

### ISSUE THREAD

**Issue by CubicTom** [CorrelAid/restatis#40]
Trying to get the full list of GP-Labels using, e.g.,  

`gp_labels <- gen_val2var(code = "GP19N1", database = "genesis")$Values`

only returns a table with 100 obs, even though there should be many more.

Is there a limit? If yes: Is there another intended way to get the full list?

Thanks and best wishes 
Thomas

**Comment by CubicTom** [comment]
Found information on the pagelength parameter here: https://correlaid.github.io/restatis/articles/additional_parameter.html

Please include this info in the helpfile, too.

Is there a need to have a maximum of 2500?

**Comment by yannikbuhl** [comment]
Sorry Thomas for the late response. We will introduce the pagelength parameter as a specific parameter in the next update. The default is 100, the maximum is 25.000. This is specified by the API.

**Comment by yannikbuhl** [comment]
The pagelength parameter has been implemented where possible. It will be available upon the next update.
