### ISSUE TITLE
Don't memoise list of current jobs

### ISSUE THREAD

**Issue by Vetrarsol** [CorrelAid/restatis#41]
Hello,

I'm just trying out restatis to access GENESIS. As usual, larger queries have to be run asynchronously as jobs. restatis provides `gen_list_jobs()` to check the status of submitted jobs; however, this uses `gen_genesis_api` (by way of `test_database_function`), which is memoised in `zzz.R`, and as far as I can tell, subsequent calls to `gen_list_jobs()`  after the first thus do not update a job statuses.

I would suggest avoiding memoisation for this particular function. Thanks!

**Comment by yannikbuhl** [comment]
Thank you so much for your input. I guess we haven't thought about that yet. We are approaching a new release in the next 2 months and will think about it. Would you be so kind as to share an example call you are making to generate the job you then want to retrieve? Thanks!

**Comment by Vetrarsol** [comment]
Thanks for getting back to me, and certainly. An example call would be `gen_table("51000-0004", database = "genesis", job = TRUE)`.

**Comment by yannikbuhl** [comment]
Perfect, thank you. I will get back to that. I have some other issues to fix before getting into it but if there is a relatively easy solution to this I am looking forward to fixing this for the next release.

**Comment by yannikbuhl** [comment]
The problem has been resolved by introducing a restatis.use_cache option. There is now a wrapper function gen_api that either uses a cached version or an uncached version depending on whether the user has set restatis.use_cache = TRUE or FALSE.

This will be available upon the upcoming release.
